//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NalburOtomasyonu.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NalburOtomasyonu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _1695df0e_9a9d_48a4_bb37_5a8013dcee2e {
            get {
                object obj = ResourceManager.GetObject("_1695df0e-9a9d-48a4-bb37-5a8013dcee2e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _1db96aa7_3975_48af_a59c_23d8b312da6c {
            get {
                object obj = ResourceManager.GetObject("_1db96aa7-3975-48af-a59c-23d8b312da6c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _1db96aa7_3975_48af_a59c_23d8b312da6c1 {
            get {
                object obj = ResourceManager.GetObject("_1db96aa7-3975-48af-a59c-23d8b312da6c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _288eb129_f4d9_4fab_a0cf_d5144dc8f810 {
            get {
                object obj = ResourceManager.GetObject("_288eb129-f4d9-4fab-a0cf-d5144dc8f810", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _288eb129_f4d9_4fab_a0cf_d5144dc8f8101 {
            get {
                object obj = ResourceManager.GetObject("_288eb129-f4d9-4fab-a0cf-d5144dc8f8101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _3022a51e_6402_4762_8dc8_576913fdbd4f {
            get {
                object obj = ResourceManager.GetObject("_3022a51e-6402-4762-8dc8-576913fdbd4f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _49a0c7e0_ebaa_42eb_9a28_5415cad404a6 {
            get {
                object obj = ResourceManager.GetObject("_49a0c7e0-ebaa-42eb-9a28-5415cad404a6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _642cd0e4_65f3_4008_bd03_903cb3006275 {
            get {
                object obj = ResourceManager.GetObject("_642cd0e4-65f3-4008-bd03-903cb3006275", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _7ae0d50f_d644_4974_aa00_ed08b7f7988b {
            get {
                object obj = ResourceManager.GetObject("_7ae0d50f-d644-4974-aa00-ed08b7f7988b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _7ae0d50f_d644_4974_aa00_ed08b7f7988b1 {
            get {
                object obj = ResourceManager.GetObject("_7ae0d50f-d644-4974-aa00-ed08b7f7988b1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _7df2ba31_6e88_493e_a409_47c08bbafa4e {
            get {
                object obj = ResourceManager.GetObject("_7df2ba31-6e88-493e-a409-47c08bbafa4e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _a123ab86_3dbf_4ddd_8b16_14c9e44c9120 {
            get {
                object obj = ResourceManager.GetObject("_a123ab86-3dbf-4ddd-8b16-14c9e44c9120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _b9c0ef71_df18_45c5_be88_98c96e342181 {
            get {
                object obj = ResourceManager.GetObject("_b9c0ef71-df18-45c5-be88-98c96e342181", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _b9c0ef71_df18_45c5_be88_98c96e3421811 {
            get {
                object obj = ResourceManager.GetObject("_b9c0ef71-df18-45c5-be88-98c96e3421811", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _da235efe_fe60_4df8_b7ca_680c9be58ad2 {
            get {
                object obj = ResourceManager.GetObject("_da235efe-fe60-4df8-b7ca-680c9be58ad2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _da235efe_fe60_4df8_b7ca_680c9be58ad21 {
            get {
                object obj = ResourceManager.GetObject("_da235efe-fe60-4df8-b7ca-680c9be58ad21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap emlak_yonetmeligi_emlakcinin_gundeminde {
            get {
                object obj = ResourceManager.GetObject("emlak-yonetmeligi-emlakcinin-gundeminde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
